### PR TITLE
Build stwo-cairo-prover on Rust 1.94 nightly

### PR DESCRIPTION
**Pull request by gilbens-starkware**
## What
Makes `stwo-cairo-prover` compile on the Rust **1.94** nightly toolchain.

## Why
Rust 1.94 removed the unstable slice `array_chunks` method (the `array_chunks` library feature is gone — `error[E0635]: unknown feature`). The upstream `stwo` 2.2.0 prover and our own witness-generation code both relied on it.

## Changes
- Point the `stwo` deps (`stwo`, `stwo-constraint-framework`, `stwo-air-utils`, `stwo-air-utils-derive`) at the 1.94-compatible stwo branch, pinned to `rev = 489a0f3e` (`gil/rust-1.94-nightly`). This is `stwo` v2.2.0 + the 1.94 compile fixes — API-identical to the published 2.2.0.
- Replace the removed slice `array_chunks::<N>()` with `as_chunks::<N>().0.iter()` in `witness/utils.rs` and the `AddressToId::array_chunks` wrapper. The `Iterator::array_chunks` adaptor uses (`memory_id_to_big.rs`) are unchanged — that's the separate `iter_array_chunks` feature, which still exists.
- Drop `array_chunks` from `prover/src/lib.rs`'s `#![feature(...)]` list (keeping `iter_array_chunks`).
- Bump `rust-toolchain.toml` to `nightly-2026-01-15`.

Branched off `0a5e70b7` (the commit currently pinned downstream by proving-utils / stwo-circuits).

## Verification
`cargo +nightly-2026-01-15 check -p stwo-cairo-prover` succeeds.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/1787)

### CODE REVIEW

**Review by Gali-StarkWare — APPROVED** [review]
:lgtm:

> @Gali-StarkWare reviewed 6 files and all commit messages, and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/1787#-:-Ouq6ozp07WyZpbKE_hP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on gilbens-starkware).
